#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render one structured analysis payload into Markdown and HTML dashboards.

Chart URLs are generated by the chart-visualization skill. This renderer does
not draw charts and deliberately validates the chart tool/args contract before
writing the Markdown report or either HTML file.
"""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from typing import Any


DARK_BACKGROUND = "#101418"
LIGHT_BACKGROUND = "#ffffff"

THEMED_TOOLS = {
    "generate_area_chart",
    "generate_bar_chart",
    "generate_boxplot_chart",
    "generate_column_chart",
    "generate_dual_axes_chart",
    "generate_fishbone_diagram",
    "generate_flow_diagram",
    "generate_funnel_chart",
    "generate_histogram_chart",
    "generate_line_chart",
    "generate_liquid_chart",
    "generate_mind_map",
    "generate_network_graph",
    "generate_organization_chart",
    "generate_pie_chart",
    "generate_radar_chart",
    "generate_sankey_chart",
    "generate_scatter_chart",
    "generate_spreadsheet",
    "generate_treemap_chart",
    "generate_venn_chart",
    "generate_violin_chart",
    "generate_word_cloud_chart",
}

COMMON_CHART_FIELDS = {"theme", "width", "height", "title"}
STYLE_FIELDS_BY_TOOL = {
    "background": {"backgroundColor", "palette", "texture"},
    "line": {"backgroundColor", "palette", "texture", "lineWidth"},
    "texture": {"texture"},
    "liquid": {"backgroundColor", "color", "texture"},
    "none": set(),
}

CHART_FIELDS = {
    "generate_area_chart": COMMON_CHART_FIELDS | {"style", "data", "stack", "axisXTitle", "axisYTitle"},
    "generate_bar_chart": COMMON_CHART_FIELDS | {"style", "data", "group", "stack", "axisXTitle", "axisYTitle"},
    "generate_boxplot_chart": COMMON_CHART_FIELDS | {"style", "data", "axisXTitle", "axisYTitle"},
    "generate_column_chart": COMMON_CHART_FIELDS | {"style", "data", "group", "stack", "axisXTitle", "axisYTitle"},
    "generate_dual_axes_chart": COMMON_CHART_FIELDS | {"style", "categories", "series", "axisXTitle"},
    "generate_fishbone_diagram": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_flow_diagram": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_funnel_chart": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_histogram_chart": COMMON_CHART_FIELDS | {"style", "data", "binNumber", "axisXTitle", "axisYTitle"},
    "generate_line_chart": COMMON_CHART_FIELDS | {"style", "data", "axisXTitle", "axisYTitle"},
    "generate_liquid_chart": COMMON_CHART_FIELDS | {"style", "percent", "shape"},
    "generate_mind_map": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_network_graph": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_organization_chart": COMMON_CHART_FIELDS | {"style", "data", "orient"},
    "generate_pie_chart": COMMON_CHART_FIELDS | {"style", "data", "innerRadius"},
    "generate_radar_chart": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_sankey_chart": COMMON_CHART_FIELDS | {"style", "data", "nodeAlign"},
    "generate_scatter_chart": COMMON_CHART_FIELDS | {"style", "data", "axisXTitle", "axisYTitle"},
    "generate_spreadsheet": {"data", "rows", "columns", "values", "theme", "width", "height"},
    "generate_treemap_chart": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_venn_chart": COMMON_CHART_FIELDS | {"style", "data"},
    "generate_violin_chart": COMMON_CHART_FIELDS | {"style", "data", "axisXTitle", "axisYTitle"},
    "generate_word_cloud_chart": COMMON_CHART_FIELDS | {"style", "data"},
}

STYLE_KIND_BY_TOOL = {
    "generate_area_chart": "line",
    "generate_bar_chart": "background",
    "generate_boxplot_chart": "background",
    "generate_column_chart": "background",
    "generate_dual_axes_chart": "background",
    "generate_fishbone_diagram": "texture",
    "generate_flow_diagram": "texture",
    "generate_funnel_chart": "background",
    "generate_histogram_chart": "background",
    "generate_line_chart": "line",
    "generate_liquid_chart": "liquid",
    "generate_mind_map": "texture",
    "generate_network_graph": "texture",
    "generate_organization_chart": "texture",
    "generate_pie_chart": "background",
    "generate_radar_chart": "line",
    "generate_sankey_chart": "background",
    "generate_scatter_chart": "background",
    "generate_spreadsheet": "none",
    "generate_treemap_chart": "background",
    "generate_venn_chart": "background",
    "generate_violin_chart": "background",
    "generate_word_cloud_chart": "background",
}

ARRAY_RECORD_RULES = {
    "generate_area_chart": ({"time", "value"}, {"group"}),
    "generate_bar_chart": ({"category", "value"}, {"group"}),
    "generate_boxplot_chart": ({"category", "value"}, {"group"}),
    "generate_column_chart": ({"category", "value"}, {"group"}),
    "generate_funnel_chart": ({"category", "value"}, set()),
    "generate_line_chart": ({"time", "value"}, {"group"}),
    "generate_pie_chart": ({"category", "value"}, set()),
    "generate_radar_chart": ({"name", "value"}, {"group"}),
    "generate_sankey_chart": ({"source", "target", "value"}, set()),
    "generate_scatter_chart": ({"x", "y"}, {"group"}),
    "generate_treemap_chart": ({"name", "value"}, {"children"}),
    "generate_venn_chart": ({"value", "sets"}, {"label"}),
    "generate_violin_chart": ({"category", "value"}, {"group"}),
    "generate_word_cloud_chart": ({"text", "value"}, set()),
}


def _text(value: Any) -> str:
    return "" if value is None else str(value)


def _fail(path: str, message: str) -> None:
    raise ValueError(f"{path}: {message}")


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _validate_optional_common_fields(args: dict[str, Any], path: str) -> None:
    for field in ("width", "height"):
        if field in args and (not _is_number(args[field]) or args[field] <= 0):
            _fail(f"{path}.{field}", "必须是正数")
    for field in ("title", "axisXTitle", "axisYTitle"):
        if field in args and not isinstance(args[field], str):
            _fail(f"{path}.{field}", "必须是 string")


def _validate_style(tool: str, style: Any, path: str) -> None:
    if not isinstance(style, dict):
        _fail(path, "必须是对象")
    allowed = STYLE_FIELDS_BY_TOOL[STYLE_KIND_BY_TOOL[tool]]
    unknown = set(style) - allowed
    if unknown:
        _fail(f"{path}", f"存在未定义字段: {', '.join(sorted(unknown))}")
    if "backgroundColor" in style:
        if not isinstance(style["backgroundColor"], str) or not style["backgroundColor"].strip():
            _fail(f"{path}.backgroundColor", "必须是非空 string")
    if "palette" in style:
        palette = style["palette"]
        if not isinstance(palette, list) or not palette or not all(
            isinstance(color, str) and color.strip() for color in palette
        ):
            _fail(f"{path}.palette", "必须是非空 string[]")
    if "texture" in style and style["texture"] not in {"default", "rough"}:
        _fail(f"{path}.texture", "必须是 default 或 rough")
    if "lineWidth" in style and (not _is_number(style["lineWidth"]) or style["lineWidth"] <= 0):
        _fail(f"{path}.lineWidth", "必须是正数")
    if "color" in style and (
        not isinstance(style["color"], str) or not style["color"].strip()
    ):
        _fail(f"{path}.color", "必须是非空 string")


def _validate_record_array(tool: str, value: Any, path: str) -> None:
    if not isinstance(value, list) or not value:
        _fail(path, "必须是至少包含一条记录的数组")
    required, optional = ARRAY_RECORD_RULES[tool]
    for index, row in enumerate(value):
        row_path = f"{path}[{index}]"
        if not isinstance(row, dict):
            _fail(row_path, "必须是对象")
        keys = set(row)
        missing = required - keys
        unknown = keys - required - optional
        if missing:
            _fail(row_path, f"缺少官方字段: {', '.join(sorted(missing))}")
        if unknown:
            _fail(row_path, f"存在未定义字段: {', '.join(sorted(unknown))}")
        for field in required:
            if field in {"value", "x", "y"} and not _is_number(row[field]):
                _fail(f"{row_path}.{field}", "必须是 number")
            if field in {"time", "category", "name", "source", "target", "text"} and not isinstance(row[field], str):
                _fail(f"{row_path}.{field}", "必须是 string")
            if field == "sets" and (
                not isinstance(row[field], list)
                or not all(isinstance(item, str) for item in row[field])
            ):
                _fail(f"{row_path}.sets", "必须是 string[]")


def _validate_tree(value: Any, path: str, allowed: set[str]) -> None:
    if not isinstance(value, dict) or not isinstance(value.get("name"), str):
        _fail(path, "必须是包含 name(string) 的对象")
    unknown = set(value) - allowed
    if unknown:
        _fail(path, f"存在未定义字段: {', '.join(sorted(unknown))}")
    children = value.get("children", [])
    if not isinstance(children, list):
        _fail(f"{path}.children", "必须是 array<object>")
    for index, child in enumerate(children):
        _validate_tree(child, f"{path}.children[{index}]", allowed)
    if "value" in value and (
        not _is_number(value["value"]) or value["value"] < 0
    ):
        _fail(f"{path}.value", "必须是非负 number")


def _validate_graph_data(value: Any, path: str) -> None:
    if not isinstance(value, dict):
        _fail(path, "必须是对象")
    if not isinstance(value.get("nodes"), list) or not value["nodes"]:
        _fail(f"{path}.nodes", "必须是非空数组")
    if not isinstance(value.get("edges"), list) or not value["edges"]:
        _fail(f"{path}.edges", "必须是非空数组")
    for index, node in enumerate(value["nodes"]):
        node_path = f"{path}.nodes[{index}]"
        if not isinstance(node, dict) or set(node) != {"name"} or not isinstance(node["name"], str):
            _fail(node_path, "必须严格包含 name(string)")
    for index, edge in enumerate(value["edges"]):
        edge_path = f"{path}.edges[{index}]"
        if not isinstance(edge, dict):
            _fail(edge_path, "必须是对象")
        unknown = set(edge) - {"source", "target", "name"}
        if unknown:
            _fail(edge_path, f"存在未定义字段: {', '.join(sorted(unknown))}")
        if not isinstance(edge.get("source"), str) or not isinstance(edge.get("target"), str):
            _fail(edge_path, "必须包含 source(string) 和 target(string)")
        if "name" in edge and not isinstance(edge["name"], str):
            _fail(f"{edge_path}.name", "必须是 string")


def _validate_args(tool: str, args: Any, path: str) -> None:
    if not isinstance(args, dict):
        _fail(path, "必须是对象")
    unknown = set(args) - CHART_FIELDS[tool]
    if unknown:
        _fail(path, f"存在未定义字段: {', '.join(sorted(unknown))}")

    _validate_optional_common_fields(args, path)

    if "style" in args:
        _validate_style(tool, args["style"], f"{path}.style")

    if tool in ARRAY_RECORD_RULES:
        _validate_record_array(tool, args.get("data"), f"{path}.data")
    elif tool == "generate_histogram_chart":
        data = args.get("data")
        if not isinstance(data, list) or not data or not all(_is_number(item) for item in data):
            _fail(f"{path}.data", "必须是至少包含一个 number 的数组")
    elif tool == "generate_liquid_chart":
        if not _is_number(args.get("percent")) or not 0 <= args["percent"] <= 1:
            _fail(f"{path}.percent", "必须是 [0,1] 范围内的 number")
    elif tool == "generate_dual_axes_chart":
        categories = args.get("categories")
        series = args.get("series")
        if not isinstance(categories, list) or not categories or not all(isinstance(item, str) for item in categories):
            _fail(f"{path}.categories", "必须是非空 string[]")
        if not isinstance(series, list) or not series:
            _fail(f"{path}.series", "必须是非空 array<object>")
        for index, item in enumerate(series):
            if not isinstance(item, dict) or set(item) - {"type", "data", "axisYTitle"}:
                _fail(f"{path}.series[{index}]", "只能使用 type、data、axisYTitle 字段")
            if item.get("type") not in {"column", "line"}:
                _fail(f"{path}.series[{index}].type", "必须是 column 或 line")
            if "axisYTitle" in item and not isinstance(item["axisYTitle"], str):
                _fail(f"{path}.series[{index}].axisYTitle", "必须是 string")
            if not isinstance(item.get("data"), list) or len(item["data"]) != len(categories):
                _fail(f"{path}.series[{index}].data", "必须是与 categories 等长的 number[]")
            if not all(_is_number(value) for value in item["data"]):
                _fail(f"{path}.series[{index}].data", "必须是 number[]")
    elif tool in {"generate_fishbone_diagram", "generate_mind_map", "generate_organization_chart"}:
        allowed_tree_fields = {
            "generate_fishbone_diagram": {"name", "children"},
            "generate_mind_map": {"name", "children"},
            "generate_organization_chart": {"name", "description", "children"},
        }[tool]
        _validate_tree(args.get("data"), f"{path}.data", allowed_tree_fields)
    elif tool in {"generate_flow_diagram", "generate_network_graph"}:
        _validate_graph_data(args.get("data"), f"{path}.data")
    elif tool == "generate_spreadsheet":
        data = args.get("data")
        rows = args.get("rows")
        has_data = isinstance(data, list) and data and all(isinstance(row, dict) for row in data)
        has_rows = (
            isinstance(rows, list)
            and rows
            and all(isinstance(row, list) and all(isinstance(cell, str) for cell in row) for row in rows)
        )
        if not (has_data or has_rows):
            _fail(
                f"{path}.data",
                "必须是非空 array<object>（官方格式），或提供 rows 二维数组（首行表头）",
            )
        if has_data and "rows" in args:
            _fail(f"{path}.rows", "data 与 rows 只能提供一个")
        for field in ("columns", "values"):
            if field in args and (
                not isinstance(args[field], list)
                or not all(isinstance(item, str) for item in args[field])
            ):
                _fail(f"{path}.{field}", "必须是 string[]")
    if tool in {"generate_bar_chart", "generate_column_chart"}:
        for field in ("group", "stack"):
            if field in args and not isinstance(args[field], bool):
                _fail(f"{path}.{field}", "必须是 boolean")
        if args.get("group") is True and args.get("stack") is True:
            _fail(path, "group 和 stack 不能同时为 true")
    if tool == "generate_liquid_chart" and "shape" in args and args["shape"] not in {
        "circle",
        "rect",
        "pin",
        "triangle",
    }:
        _fail(f"{path}.shape", "必须是 circle、rect、pin 或 triangle")
    if tool == "generate_organization_chart" and "orient" in args and args["orient"] not in {
        "horizontal",
        "vertical",
    }:
        _fail(f"{path}.orient", "必须是 horizontal 或 vertical")
    if tool == "generate_pie_chart" and "innerRadius" in args and (
        not _is_number(args["innerRadius"]) or not 0 <= args["innerRadius"] <= 1
    ):
        _fail(f"{path}.innerRadius", "必须是 [0,1] 范围内的 number")
    if tool == "generate_histogram_chart" and "binNumber" in args and (
        not _is_number(args["binNumber"]) or args["binNumber"] <= 0
    ):
        _fail(f"{path}.binNumber", "必须是正数")
    if tool == "generate_sankey_chart" and "nodeAlign" in args and args["nodeAlign"] not in {
        "left",
        "right",
        "justify",
        "center",
    }:
        _fail(f"{path}.nodeAlign", "必须是 left、right、justify 或 center")


def _validate_chart(chart: Any, index: int) -> None:
    path = f"charts[{index}]"
    if not isinstance(chart, dict):
        _fail(path, "必须是对象")
    allowed = {"tool", "title", "alt", "args"}
    unknown = set(chart) - allowed
    if unknown:
        _fail(path, f"存在未定义字段: {', '.join(sorted(unknown))}")
    tool = chart.get("tool")
    if tool not in THEMED_TOOLS:
        _fail(f"{path}.tool", "必须使用 chart-visualization 支持的主题图表工具")
    if "args" not in chart or not isinstance(chart["args"], dict):
        _fail(f"{path}.args", "必须提供 args 对象")
    _validate_args(tool, chart["args"], f"{path}.args")


def _theme_invariant_args(args: dict[str, Any]) -> dict[str, Any]:
    return dict(args)


def _list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _normalize_chart(chart: Any) -> dict[str, Any] | None:
    """Accept both strict {tool,title,alt,args} and section-local shorthand.

    Historical prompts for ``render_html_report`` asked agents to produce
    ``sections[].charts[]`` with chart args flattened onto the chart object
    (for example ``{tool,title,alt,data:[...]}``).  The renderer validates the
    official chart tool args contract, so normalize that product-facing
    contract before validation/rendering instead of leaking raw objects into
    HTML.
    """
    if not isinstance(chart, dict):
        return None
    tool = chart.get("tool")
    if tool not in THEMED_TOOLS:
        return dict(chart)
    args = dict(chart.get("args")) if isinstance(chart.get("args"), dict) else {}
    for field in CHART_FIELDS[tool]:
        if field in chart and field not in {"title"}:
            args.setdefault(field, chart[field])
    title = _text(chart.get("title") or args.get("title") or "图表")
    if "title" in CHART_FIELDS[tool] and title:
        args.setdefault("title", title)
    return {
        "tool": tool,
        "title": title,
        "alt": _text(chart.get("alt") or title),
        "args": args,
    }


def _normalize_payload(payload: dict[str, Any]) -> dict[str, Any]:
    out = dict(payload)

    assessment = payload.get("assessment")
    if isinstance(assessment, dict):
        out["assessment"] = _text(
            assessment.get("label")
            or assessment.get("summary")
            or assessment.get("value")
            or "未提供"
        )
        if not out.get("risk_level"):
            out["risk_level"] = assessment.get("risk_level") or assessment.get("risk")

    top_charts = [
        normalized
        for chart in _list(payload.get("charts"))
        if (normalized := _normalize_chart(chart)) is not None
    ]
    all_charts = list(top_charts)

    sections: list[dict[str, Any]] = []
    for index, raw_section in enumerate(_list(payload.get("sections"))):
        if not isinstance(raw_section, dict):
            continue
        section = dict(raw_section)
        section.setdefault("id", f"section-{index + 1}")
        section_charts = [
            normalized
            for chart in _list(section.get("charts"))
            if (normalized := _normalize_chart(chart)) is not None
        ]
        section["charts"] = section_charts
        all_charts.extend(section_charts)
        sections.append(section)
    out["sections"] = sections
    out["charts"] = top_charts
    out["_all_charts"] = all_charts

    if not _list(out.get("data_overview")):
        overview: list[dict[str, str]] = []
        for section in sections:
            for metric in _list(section.get("metrics")):
                if not isinstance(metric, dict):
                    continue
                unit = _text(metric.get("unit"))
                overview.append(
                    {
                        "metric": _text(metric.get("label") or metric.get("name") or metric.get("id") or "指标"),
                        "current": f"{_text(metric.get('value', '—'))}{unit}",
                        "change": _text(metric.get("source") or "—"),
                        "yoy": _text(metric.get("as_of") or "—"),
                    }
                )
        if overview:
            out["data_overview"] = overview

    return out


def validate_payload(payload: dict[str, Any]) -> None:
    charts = payload.get("_all_charts") or payload.get("charts")
    if not isinstance(charts, list) or len(charts) < 3:
        _fail("charts", "完整看板必须至少包含 3 个图表")
    for index, chart in enumerate(charts):
        _validate_chart(chart, index)


# ── 内嵌 SVG 图表（离线渲染：无外部 URL，数据内嵌）──────────────────
_SVG_PALETTE = {
    "dark": ["#e8a33d", "#5ab0ff", "#6fce8f", "#ff7b7b", "#c792ea", "#f5a6c8", "#8ee6c8", "#ffd166"],
    "light": ["#b47b26", "#2f7fd4", "#3a9d5d", "#d64545", "#7b4fc0", "#c95f8e", "#1f9c8e", "#8a6d00"],
}
_SVG_W, _SVG_H = 560, 280
_SVG_L, _SVG_R, _SVG_T, _SVG_B = 52, 16, 20, 46


def _svg_esc(value: Any) -> str:
    return html.escape(_text(value), quote=True)


def _svg_fg(variant: str) -> str:
    return "#edf2f4" if variant == "dark" else "#18212a"


def _svg_grid(variant: str) -> str:
    return "#34414b" if variant == "dark" else "#d7dee3"


def _svg_palette(variant: str) -> list[str]:
    return _SVG_PALETTE.get(variant, _SVG_PALETTE["light"])


def _svg_legend(entries: list[tuple[str, str]], variant: str) -> str:
    items, x = [], 4
    y = _SVG_H - 10
    for label, color in entries:
        items.append(
            f'<rect x="{x}" y="{y - 9}" width="10" height="10" fill="{color}"/>'
            f'<text x="{x + 14}" y="{y}" font-size="11" fill="{_svg_fg(variant)}">{_svg_esc(label)}</text>'
        )
        x += 14 + 11 * len(label) + 10
    return "".join(items)


def _svg_y_axis(lo: float, hi: float, variant: str) -> str:
    ticks = []
    for i in range(4):
        v = lo + (hi - lo) * i / 3
        y = _SVG_T + (hi - v) * (_SVG_H - _SVG_T - _SVG_B) / (hi - lo)
        ticks.append(
            f'<line x1="{_SVG_L}" y1="{y:.1f}" x2="{_SVG_W - _SVG_R}" y2="{y:.1f}" stroke="{_svg_grid(variant)}" stroke-dasharray="2,3"/>'
            f'<text x="{_SVG_L - 6}" y="{y + 4:.1f}" font-size="10" text-anchor="end" fill="{_svg_fg(variant)}">{v:g}</text>'
        )
    return "".join(ticks)


def _svg_line_chart(args: dict[str, Any], variant: str, alt: str = "") -> str:
    rows = args.get("data") or []
    palette = _svg_palette(variant)
    groups: dict[str, list[tuple[str, float]]] = {}
    for row in rows:
        groups.setdefault(str(row.get("group", "主序列")), []).append((str(row["time"]), float(row["value"])))
    all_y = [v for g in groups.values() for _, v in g]
    lo, hi = min(all_y), max(all_y)
    span = (hi - lo) or 1.0
    lo -= span * 0.1
    hi += span * 0.1
    n = max(len(groups.get(next(iter(groups)), [])), 1)

    def x_at(i: int) -> float:
        return _SVG_L + i * (_SVG_W - _SVG_L - _SVG_R) / max(n - 1, 1)

    def y_at(v: float) -> float:
        return _SVG_T + (hi - v) * (_SVG_H - _SVG_T - _SVG_B) / (hi - lo)

    parts = [_svg_y_axis(lo, hi, variant)]
    for index, (label, pts) in enumerate(groups.items()):
        color = palette[index % len(palette)]
        coords = " ".join(f"{x_at(i):.1f},{y_at(v):.1f}" for i, (_, v) in enumerate(pts))
        parts.append(f'<polyline points="{coords}" fill="none" stroke="{color}" stroke-width="2"/>')
    labels = groups.get(next(iter(groups)), [])
    step = max(len(labels) // 6, 1)
    for i, (x_label, _) in enumerate(labels):
        if i % step == 0:
            parts.append(
                f'<text x="{x_at(i):.1f}" y="{_SVG_H - _SVG_B + 14}" font-size="10" text-anchor="middle" fill="{_svg_fg(variant)}">{_svg_esc(x_label)}</text>'
            )
    parts.append(_svg_legend([(label, palette[i % len(palette)]) for i, label in enumerate(groups)], variant))
    return (
        f'<svg viewBox="0 0 {_SVG_W} {_SVG_H}" role="img" aria-label="{_svg_esc(alt)}" style="max-width:100%;height:auto">'
        + "".join(parts) + "</svg>"
    )


def _svg_bar_chart(args: dict[str, Any], variant: str, alt: str = "") -> str:
    rows = args.get("data") or []
    palette = _svg_palette(variant)
    values = [float(r["value"]) for r in rows]
    lo, hi = min(0.0, min(values)), max(0.0, max(values))
    span = (hi - lo) or 1.0
    lo -= span * 0.1
    hi += span * 0.1
    n = len(rows)
    slot = (_SVG_W - _SVG_L - _SVG_R) / n
    bar_w = min(slot * 0.6, 48)

    def y_at(v: float) -> float:
        return _SVG_T + (hi - v) * (_SVG_H - _SVG_T - _SVG_B) / (hi - lo)

    parts = [_svg_y_axis(lo, hi, variant)]
    baseline = y_at(0.0)
    for i, row in enumerate(rows):
        color = palette[i % len(palette)]
        x = _SVG_L + i * slot + (slot - bar_w) / 2
        value_y = y_at(float(row["value"]))
        y = min(value_y, baseline)
        height = abs(baseline - value_y)
        parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{height:.1f}" fill="{color}"/>')
        parts.append(
            f'<text x="{x + bar_w / 2:.1f}" y="{_SVG_H - _SVG_B + 14}" font-size="10" text-anchor="middle" fill="{_svg_fg(variant)}">{_svg_esc(row.get("category", ""))}</text>'
        )
    return (
        f'<svg viewBox="0 0 {_SVG_W} {_SVG_H}" role="img" aria-label="{_svg_esc(alt)}" style="max-width:100%;height:auto">'
        + "".join(parts) + "</svg>"
    )


def _svg_pie_chart(args: dict[str, Any], variant: str, alt: str = "") -> str:
    import math as _math

    rows = args.get("data") or []
    palette = _svg_palette(variant)
    total = sum(float(r["value"]) for r in rows) or 1.0
    cx, cy, radius = 190, 140, 96
    angle = -90.0
    parts = []
    legend: list[tuple[str, str]] = []
    for i, row in enumerate(rows):
        color = palette[i % len(palette)]
        sweep = 360.0 * float(row["value"]) / total
        a1, a2 = angle, angle + sweep
        rad1, rad2 = _math.radians(a1), _math.radians(a2)
        x1, y1 = cx + radius * _math.cos(rad1), cy + radius * _math.sin(rad1)
        x2, y2 = cx + radius * _math.cos(rad2), cy + radius * _math.sin(rad2)
        large = 1 if sweep > 180 else 0
        parts.append(
            f'<path d="M {cx} {cy} L {x1:.1f} {y1:.1f} A {radius} {radius} 0 {large} 1 {x2:.1f} {y2:.1f} Z" fill="{color}"/>'
        )
        legend.append((f"{row.get('category', '')} {row['value']:g}", color))
        angle += sweep
    parts.append(_svg_legend(legend, variant))
    return (
        f'<svg viewBox="0 0 {_SVG_W} {_SVG_H}" role="img" aria-label="{_svg_esc(alt)}" style="max-width:100%;height:auto">'
        + "".join(parts) + "</svg>"
    )


def _svg_radar_chart(args: dict[str, Any], variant: str, alt: str = "") -> str:
    rows = args.get("data") or []
    palette = _svg_palette(variant)
    n = len(rows)
    if n < 3:
        return _svg_spreadsheet(args, variant, alt)
    cx, cy, radius = 280, 140, 100

    def point(i: int, r: float) -> tuple[float, float]:
        import math as _math
        a = _math.radians(-90 + 360 * i / n)
        return cx + r * _math.cos(a), cy + r * _math.sin(a)

    parts = []
    for ring in (0.25, 0.5, 0.75, 1.0):
        pts = " ".join(f"{point(i, radius * ring)[0]:.1f},{point(i, radius * ring)[1]:.1f}" for i in range(n))
        parts.append(f'<polygon points="{pts}" fill="none" stroke="{_svg_grid(variant)}"/>')
    values = [float(r["value"]) for r in rows]
    hi = max(values) or 1.0
    polygon = " ".join(
        f"{point(i, radius * values[i] / hi)[0]:.1f},{point(i, radius * values[i] / hi)[1]:.1f}" for i in range(n)
    )
    color = palette[0]
    parts.append(f'<polygon points="{polygon}" fill="{color}" fill-opacity="0.35" stroke="{color}" stroke-width="2"/>')
    for i, row in enumerate(rows):
        x, y = point(i, radius + 22)
        parts.append(
            f'<text x="{x:.1f}" y="{y:.1f}" font-size="11" text-anchor="middle" fill="{_svg_fg(variant)}">{_svg_esc(row.get("name", ""))}</text>'
        )
    return (
        f'<svg viewBox="0 0 {_SVG_W} {_SVG_H}" role="img" aria-label="{_svg_esc(alt)}" style="max-width:100%;height:auto">'
        + "".join(parts) + "</svg>"
    )


def _svg_scatter_chart(args: dict[str, Any], variant: str, alt: str = "") -> str:
    rows = args.get("data") or []
    palette = _svg_palette(variant)
    xs = [float(r["x"]) for r in rows]
    ys = [float(r["y"]) for r in rows]
    x_lo, x_hi = min(xs), max(xs)
    y_lo, y_hi = min(ys), max(ys)
    x_span = (x_hi - x_lo) or 1.0
    y_span = (y_hi - y_lo) or 1.0
    x_lo -= x_span * 0.1
    x_hi += x_span * 0.1
    y_lo -= y_span * 0.1
    y_hi += y_span * 0.1

    def x_at(v: float) -> float:
        return _SVG_L + (v - x_lo) * (_SVG_W - _SVG_L - _SVG_R) / (x_hi - x_lo)

    def y_at(v: float) -> float:
        return _SVG_T + (y_hi - v) * (_SVG_H - _SVG_T - _SVG_B) / (y_hi - y_lo)

    parts = [_svg_y_axis(y_lo, y_hi, variant)]
    for i, row in enumerate(rows):
        color = palette[i % len(palette)]
        parts.append(f'<circle cx="{x_at(float(row["x"])):.1f}" cy="{y_at(float(row["y"])):.1f}" r="4" fill="{color}"/>')
    return (
        f'<svg viewBox="0 0 {_SVG_W} {_SVG_H}" role="img" aria-label="{_svg_esc(alt)}" style="max-width:100%;height:auto">'
        + "".join(parts) + "</svg>"
    )


def _svg_spreadsheet(args: dict[str, Any], variant: str, alt: str) -> str:
    """渲染结构化表格（generate_spreadsheet）。

    支持两种输入格式：
    - ``data``: array<object>（官方格式），每行一个对象，键为列名，``columns`` 可选指定列序；
    - ``rows``: string[][]（二维数组），首行即表头。
    """
    data = args.get("data")
    rows_2d = args.get("rows")
    headers: list[str] = []
    body_rows: list[list[str]] = []
    if isinstance(data, list) and data and all(isinstance(row, dict) for row in data):
        columns = args.get("columns") or []
        headers = [c for c in columns if any(c in row for row in data)] or sorted(
            {k for row in data for k in row.keys()}
        )
        body_rows = [[_text(row.get(h, "")) for h in headers] for row in data]
    elif isinstance(rows_2d, list) and rows_2d:
        headers = [_text(cell) for cell in rows_2d[0]]
        body_rows = [[_text(cell) for cell in row] for row in rows_2d[1:]]
    if not headers:
        return f'<p role="img" aria-label="{_svg_esc(alt)}">{_svg_esc("无数据")}</p>'
    border = "1px solid " + _svg_grid(variant)
    fg = _svg_fg(variant)
    th_bg = _svg_grid(variant)
    head = "".join(f"<th style='padding:6px 10px;text-align:left;background:{th_bg};color:{fg};border:{border}'>{_svg_esc(h)}</th>" for h in headers)
    body = "".join(
        "<tr>"
        + "".join(f"<td style='padding:6px 10px;border:{border}'>{_svg_esc(cell)}</td>" for cell in row)
        + "</tr>"
        for row in body_rows
    )
    return (
        f'<div class="table-scroll" role="img" aria-label="{_svg_esc(alt)}">'
        f'<table style="border-collapse:collapse;font-size:12px;color:{fg};min-width:100%;width:max-content">'
        f"<thead><tr style='border-bottom:2px solid {_svg_grid(variant)}'>{head}</tr></thead>"
        f"<tbody>{body}</tbody></table></div>"
    )


def _svg_chart(tool: str, args: dict[str, Any], variant: str, alt: str) -> str:
    """渲染内嵌图表：常用类型生成 SVG，其余降级为结构化表格。"""
    try:
        if tool == "generate_line_chart":
            return _svg_line_chart(args, variant, alt)
        if tool == "generate_area_chart":
            return _svg_line_chart(args, variant, alt)
        if tool in {"generate_bar_chart", "generate_column_chart"}:
            return _svg_bar_chart(args, variant, alt)
        if tool == "generate_pie_chart":
            return _svg_pie_chart(args, variant, alt)
        if tool == "generate_radar_chart":
            return _svg_radar_chart(args, variant, alt)
        if tool == "generate_scatter_chart":
            return _svg_scatter_chart(args, variant, alt)
        if tool == "generate_spreadsheet":
            return _svg_spreadsheet(args, variant, alt)
        return _svg_spreadsheet(args, variant, alt)
    except Exception:
        return _svg_spreadsheet(args, variant, alt)


def _render_chart_card(chart: dict[str, Any], variant: str, esc) -> str:
    return (
        f'<section class="chart"><h3>{esc(chart.get("title", "图表"))}</h3>'
        f'{_svg_chart(chart.get("tool", ""), chart.get("args") or {}, variant, chart.get("alt", chart.get("title", "图表")))}</section>'
    )


def _render_text_item(item: Any, esc, body_keys: tuple[str, ...]) -> str:
    if isinstance(item, dict):
        title = esc(item.get("title") or item.get("label") or item.get("name") or "")
        body = ""
        for key in body_keys:
            if item.get(key):
                body = esc(item.get(key))
                break
        if title and body:
            return f"<li><strong>{title}</strong><p>{body}</p></li>"
        if title:
            return f"<li><strong>{title}</strong></li>"
        if body:
            return f"<li>{body}</li>"
        return ""
    text = esc(item)
    return f"<li>{text}</li>" if text else ""


def _render_reference_item(item: Any, esc) -> str:
    if isinstance(item, dict):
        title = esc(item.get("title") or item.get("source") or item.get("url") or "参考资料")
        source = esc(item.get("source") or "")
        as_of = esc(item.get("as_of") or item.get("date") or "")
        url = item.get("url")
        label = f'<a href="{esc(url)}" rel="noreferrer" target="_blank">{title}</a>' if isinstance(url, str) and url else title
        meta = " · ".join(part for part in (source, as_of) if part)
        return f"<li>{label}{f'<small>{meta}</small>' if meta else ''}</li>"
    text = esc(item)
    return f"<li>{text}</li>" if text else ""


def _render_metric(metric: Any, esc) -> str:
    if not isinstance(metric, dict):
        return ""
    label = esc(metric.get("label") or metric.get("name") or metric.get("id") or "指标")
    value = esc(_text(metric.get("value", "—")) + _text(metric.get("unit") or ""))
    source = esc(metric.get("source") or metric.get("as_of") or "")
    return f'<div class="metric"><span>{label}</span><strong>{value}</strong>{f"<small>{source}</small>" if source else ""}</div>'


def _render_section(section: dict[str, Any], variant: str, esc) -> str:
    title = esc(section.get("title") or section.get("id") or "分析分区")
    status = esc(section.get("status") or "")
    summary = esc(section.get("summary") or "")
    metrics = "".join(_render_metric(metric, esc) for metric in _list(section.get("metrics")))
    charts = "".join(
        _render_chart_card(chart, variant, esc)
        for chart in _list(section.get("charts"))
        if isinstance(chart, dict)
    )
    evidence = "".join(_render_text_item(item, esc, ("content", "detail", "summary")) for item in _list(section.get("evidence")))
    gaps = "".join(_render_text_item(item, esc, ("content", "detail", "summary")) for item in _list(section.get("gaps")))
    return (
        f'<section class="section report-section" id="{esc(section.get("id") or title)}">'
        f"<div class=\"section-head\"><h2>{title}</h2>{f'<span>{status}</span>' if status else ''}</div>"
        f"{f'<p class=\"section-summary\">{summary}</p>' if summary else ''}"
        f"{f'<div class=\"metrics\">{metrics}</div>' if metrics else ''}"
        f"{f'<div class=\"charts\">{charts}</div>' if charts else ''}"
        f"{f'<details><summary>证据与数据源</summary><ul>{evidence}</ul></details>' if evidence else ''}"
        f"{f'<details><summary>数据缺口</summary><ul>{gaps}</ul></details>' if gaps else ''}"
        "</section>"
    )


def _html(payload: dict[str, Any], variant: str) -> str:
    esc = lambda value: html.escape(_text(value), quote=True)
    title = esc(payload.get("title", "分析报告"))
    generated_at = esc(payload.get("generated_at", ""))
    summary = esc(payload.get("summary", ""))
    assessment = esc(payload.get("assessment", "未提供"))
    risk_level = esc(payload.get("risk_level", "未提供"))
    overview = payload.get("data_overview") or []
    sections = payload.get("sections") or []
    core = payload.get("core_analysis") or []
    risks = payload.get("risks") or []
    references = payload.get("references") or []
    charts = payload.get("charts") or []
    dark = variant == "dark"
    background = DARK_BACKGROUND if dark else LIGHT_BACKGROUND
    panel = "#1a2229" if dark else "#ffffff"
    text = "#edf2f4" if dark else "#18212a"
    muted = "#9aa8b2" if dark else "#65727d"
    line = "#34414b" if dark else "#d7dee3"

    kpis = "".join(
        f'<div class="kpi"><span>{esc(row.get("metric", "指标"))}</span>'
        f'<strong>{esc(row.get("current", "—"))}</strong>'
        f'<small>{esc(row.get("change", "—"))}</small></div>'
        for row in overview[:6]
    )
    chart_cards = "".join(_render_chart_card(chart, variant, esc) for chart in charts if isinstance(chart, dict))
    section_cards = "".join(_render_section(section, variant, esc) for section in sections if isinstance(section, dict))
    core_items = "".join(_render_text_item(item, esc, ("content", "detail", "summary")) for item in core) or "<li>暂无。</li>"
    risk_items = "".join(_render_text_item(item, esc, ("detail", "content", "summary")) for item in risks) or "<li>暂无。</li>"
    reference_items = "".join(_render_reference_item(item, esc) for item in references) or "<li>未提供。</li>"
    nav_items = "".join(
        f'<a href="#{esc(section.get("id") or f"section-{index + 1}")}">{esc(section.get("title") or f"分区 {index + 1}")}</a>'
        for index, section in enumerate(sections)
        if isinstance(section, dict)
    )

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
:root {{ color-scheme: {"dark" if dark else "light"}; --bg:{background}; --panel:{panel}; --line:{line}; --muted:{muted}; --text:{text}; --accent:#b47b26; }}
* {{ box-sizing:border-box; }}
html,body {{ max-width:100%; overflow-x:hidden; }}
body {{ margin:0; background:var(--bg); color:var(--text); font:15px/1.7 -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif; }}
main {{ max-width:1180px; margin:0 auto; padding:28px 22px 42px; }}
header {{ border-bottom:1px solid var(--line); padding:8px 0 22px; margin-bottom:20px; }}
h1 {{ margin:0 0 6px; font-size:28px; }}
h2 {{ margin:0 0 12px; font-size:17px; color:var(--accent); }}
h3 {{ margin:0 0 12px; font-size:15px; color:var(--accent); }}
a {{ color:var(--accent); }}
.meta,.muted {{ color:var(--muted); }}
.summary {{ background:var(--panel); border-left:3px solid var(--accent); padding:16px 18px; margin-bottom:18px; }}
.nav {{ display:flex; gap:8px; flex-wrap:wrap; margin:0 0 18px; }}
.nav a {{ border:1px solid var(--line); border-radius:999px; padding:5px 10px; text-decoration:none; color:var(--text); background:var(--panel); }}
.kpis {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin-bottom:18px; }}
.kpi,.metric,.chart,.section {{ background:var(--panel); border:1px solid var(--line); padding:16px; }}
.kpi span,.kpi small,.metric span,.metric small {{ display:block; color:var(--muted); }}
.kpi strong,.metric strong {{ display:block; font-size:24px; margin:2px 0; }}
.metrics {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:10px; margin:12px 0 16px; }}
.charts {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(320px,1fr)); gap:14px; margin-bottom:18px; }}
.chart img {{ display:block; width:100%; height:auto; background:{background}; }}
.chart {{ min-width:0; overflow:hidden; }}
.table-scroll {{ width:100%; max-width:100%; overflow-x:auto; -webkit-overflow-scrolling:touch; }}
.section {{ margin-top:14px; }}
.section-head {{ display:flex; justify-content:space-between; gap:12px; align-items:flex-start; border-bottom:1px solid var(--line); margin:-2px 0 12px; }}
.section-head span {{ color:var(--muted); font-size:12px; border:1px solid var(--line); border-radius:999px; padding:2px 8px; }}
.section-summary {{ margin-top:0; }}
li {{ margin:5px 0; }}
li p {{ margin:4px 0 0; }}
li small {{ display:block; color:var(--muted); margin-top:2px; }}
details {{ border-top:1px solid var(--line); margin-top:12px; padding-top:8px; }}
summary {{ color:var(--muted); cursor:pointer; }}
footer {{ color:var(--muted); font-size:12px; border-top:1px solid var(--line); margin-top:24px; padding-top:14px; }}
@media (max-width: 640px) {{
  main {{ padding:18px 14px 32px; }}
  h1 {{ font-size:23px; }}
  .charts {{ grid-template-columns:minmax(0,1fr); }}
}}
</style>
</head>
<body data-theme="{variant}">
<main>
<header><h1>{title}</h1><div class="meta">生成时间：{generated_at}</div></header>
<div class="summary"><h2>执行摘要</h2><p>{summary}</p><div class="muted">综合评估：{assessment}　风险等级：{risk_level}</div></div>
{f'<nav class="nav" aria-label="报告分区">{nav_items}</nav>' if nav_items else ''}
<div class="kpis">{kpis}</div>
{f'<div class="charts">{chart_cards}</div>' if chart_cards else ''}
{section_cards}
<section class="section"><h2>核心分析</h2><ul>{core_items}</ul></section>
<section class="section"><h2>风险提示</h2><ul>{risk_items}</ul></section>
<section class="section"><h2>参考资料</h2><ul>{reference_items}</ul></section>
<footer>以上分析基于公开数据与逻辑推演，不构成投资建议。</footer>
</main>
</body>
</html>
"""


def _markdown(payload: dict[str, Any]) -> str:
    title = _text(payload.get("title", "分析报告"))
    generated_at = _text(payload.get("generated_at", ""))
    summary = _text(payload.get("summary", ""))
    assessment = _text(payload.get("assessment", "未提供"))
    risk_level = _text(payload.get("risk_level", "未提供"))
    overview = payload.get("data_overview") or []
    sections = payload.get("sections") or []
    core = payload.get("core_analysis") or []
    risks = payload.get("risks") or []
    references = payload.get("references") or []

    lines = [
        f"# {title}",
        "",
        f"**生成时间**: {generated_at}",
        "",
        "## 执行摘要",
        "",
        summary or "未提供。",
        "",
        f"- 综合评估：{assessment}",
        f"- 风险等级：{risk_level}",
        "",
        "## 数据概览",
        "",
        "| 指标 | 当前值 | 变化 | 同比 |",
        "|---|---:|---:|---:|",
    ]
    for row in overview:
        if not isinstance(row, dict):
            continue
        lines.append(
            "| "
            + " | ".join([
                _text(row.get("metric", "指标")),
                _text(row.get("current", "—")),
                _text(row.get("change", "—")),
                _text(row.get("yoy", "—")),
            ])
            + " |"
        )
    for section in sections:
        if not isinstance(section, dict):
            continue
        lines.extend(["", f"## {_text(section.get('title') or section.get('id') or '分析分区')}", ""])
        if section.get("summary"):
            lines.extend([_text(section.get("summary")), ""])
        metrics = [m for m in _list(section.get("metrics")) if isinstance(m, dict)]
        if metrics:
            lines.extend(["| 指标 | 数值 | 来源 | 截止 |", "|---|---:|---|---|"])
            for metric in metrics:
                lines.append(
                    "| "
                    + " | ".join([
                        _text(metric.get("label") or metric.get("name") or metric.get("id") or "指标"),
                        _text(metric.get("value", "—")) + _text(metric.get("unit") or ""),
                        _text(metric.get("source") or "—"),
                        _text(metric.get("as_of") or "—"),
                    ])
                    + " |"
                )
            lines.append("")
        for chart in _list(section.get("charts")):
            if isinstance(chart, dict):
                lines.append(f"- 图表：{_text(chart.get('title') or chart.get('alt') or chart.get('tool'))}")
    lines.extend(["", "## 核心分析", ""])
    core_lines = [_markdown_text_item(item, ("content", "detail", "summary"), index) for index, item in enumerate(core, start=1)]
    lines.extend([line for line in core_lines if line] or ["暂无。"])
    lines.extend(["", "## 风险提示", ""])
    risk_lines = [_markdown_text_item(item, ("detail", "content", "summary")) for item in risks]
    lines.extend([line for line in risk_lines if line] or ["- 暂无。"])
    lines.extend(["", "## 参考资料", ""])
    ref_lines = [_markdown_reference_item(item) for item in references]
    lines.extend([line for line in ref_lines if line] or ["- 未提供。"])
    lines.extend([
        "",
        "## 免责与风险提示",
        "",
        "以上分析基于公开数据与逻辑推演，不构成投资建议。",
        "",
    ])
    return "\n".join(lines)


def _markdown_text_item(item: Any, body_keys: tuple[str, ...], index: int | None = None) -> str:
    prefix = f"{index}. " if index is not None else "- "
    if isinstance(item, dict):
        title = _text(item.get("title") or item.get("label") or item.get("name") or "")
        body = ""
        for key in body_keys:
            if item.get(key):
                body = _text(item.get(key))
                break
        if title and body:
            return f"{prefix}**{title}**：{body}"
        if title:
            return f"{prefix}{title}"
        if body:
            return f"{prefix}{body}"
        return ""
    text = _text(item)
    return f"{prefix}{text}" if text else ""


def _markdown_reference_item(item: Any) -> str:
    if isinstance(item, dict):
        title = _text(item.get("title") or item.get("source") or item.get("url") or "参考资料")
        source = _text(item.get("source") or "")
        as_of = _text(item.get("as_of") or item.get("date") or "")
        url = _text(item.get("url") or "")
        text = f"[{title}]({url})" if url else title
        meta = " · ".join(part for part in (source, as_of) if part)
        return f"- {text}{f'（{meta}）' if meta else ''}"
    text = _text(item)
    return f"- {text}" if text else ""


def render(input_path: Path, output_dir: Path, basename: str) -> tuple[Path, Path, Path]:
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("报告输入必须是 JSON 对象")
    payload = _normalize_payload(payload)
    validate_payload(payload)
    output_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = output_dir / f"{basename}.md"
    dark_path = output_dir / f"{basename}-dark.html"
    light_path = output_dir / f"{basename}-light.html"
    markdown_path.write_text(_markdown(payload), encoding="utf-8")
    dark_path.write_text(_html(payload, "dark"), encoding="utf-8")
    light_path.write_text(_html(payload, "light"), encoding="utf-8")
    return markdown_path, dark_path, light_path


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 Markdown 报告与深浅 HTML 分析看板")
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--output-dir", required=True, type=Path)
    parser.add_argument("--basename", required=True)
    args = parser.parse_args()
    try:
        markdown_path, dark_path, light_path = render(args.input, args.output_dir, args.basename)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        parser.error(str(exc))
    print(f"Markdown: {markdown_path}")
    print(f"Dark HTML: {dark_path}")
    print(f"Light HTML: {light_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
