from __future__ import annotations

import hashlib
import json
import platform
import shutil
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]


@dataclass(frozen=True)
class DataSpaceInfo:
    app_data_dir: Path
    active_user_id: str
    qilin_home: Path
    qilin_data_dir: Path
    runtime_config_path: Path
    product_db_path: Path
    skill_root: Path
    is_development_fallback: bool


class KStockDataSpace:
    def __init__(
        self,
        app_data_dir: Path,
        *,
        skill_root: Path | None = None,
        repo_root: Path | None = None,
        development_fallback: bool = False,
    ) -> None:
        self.app_data_dir = Path(app_data_dir).resolve()
        self.skill_root = Path(skill_root or REPO_ROOT / "vendor/skills").resolve()
        self.repo_root = Path(repo_root or REPO_ROOT).resolve()
        self.development_fallback = development_fallback

    def ensure(self) -> DataSpaceInfo:
        self.migrate_development_qilin_if_empty()

        config_dir = self.app_data_dir / "config"
        qilin_home = self.app_data_dir / "runtime/qilin"
        qilin_data_dir = qilin_home / "data"
        product_dir = self.app_data_dir / "product"

        for directory in (
            config_dir,
            qilin_data_dir,
            qilin_home / "users",
            product_dir,
            product_dir / "exports",
            product_dir / "report-index",
            self.app_data_dir / "cache/market-data",
            self.app_data_dir / "cache/skill-scan",
            self.app_data_dir / "cache/thumbnails",
            self.app_data_dir / "logs",
            self.app_data_dir / "backups",
        ):
            directory.mkdir(parents=True, exist_ok=True)

        active_user_id = self._load_or_create_user_id(config_dir / "kstock.settings.json")
        (qilin_home / "users" / active_user_id).mkdir(parents=True, exist_ok=True)

        info = DataSpaceInfo(
            app_data_dir=self.app_data_dir,
            active_user_id=active_user_id,
            qilin_home=qilin_home,
            qilin_data_dir=qilin_data_dir,
            runtime_config_path=config_dir / "qilin.runtime.yaml",
            product_db_path=product_dir / "kstock.db",
            skill_root=self.skill_root,
            is_development_fallback=self.development_fallback,
        )
        self.write_runtime_config(info)
        return info

    def _load_or_create_user_id(self, settings_path: Path) -> str:
        if settings_path.is_file():
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
            active_user_id = str(settings.get("activeUserId", "")).strip()
            if active_user_id:
                return active_user_id

        seed = f"{platform.node()}:{self.app_data_dir}".encode("utf-8")
        active_user_id = f"local-{hashlib.sha256(seed).hexdigest()[:12]}"
        settings_path.write_text(
            json.dumps(
                {"activeUserId": active_user_id, "schemaVersion": 1},
                ensure_ascii=True,
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return active_user_id

    def migrate_development_qilin_if_empty(self) -> bool:
        source = self.repo_root / ".kstock/qilin"
        target = self.app_data_dir / "runtime/qilin"
        state_path = self.app_data_dir / "config/migration-state.json"
        state_path.parent.mkdir(parents=True, exist_ok=True)

        if state_path.is_file() or not source.is_dir():
            return False
        if target.exists() and any(target.iterdir()):
            state_path.write_text(
                json.dumps({"developmentQilinMigration": "skipped-target-not-empty"}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            return False

        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(source, target)
        state_path.write_text(
            json.dumps({"developmentQilinMigration": "copied"}, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        return True

    def write_runtime_config(self, info: DataSpaceInfo) -> None:
        content = f"""# Generated by KStock. Do not edit vendor or upstream config files.
config_version: 31
log_level: info

token_usage:
  enabled: true

token_budget:
  enabled: false
  max_tokens: 200000
  max_input_tokens: null
  max_output_tokens: null
  warn_threshold: 0.8
  hard_stop_threshold: 1.0

max_recursion_limit: 1000

models: []

database:
  backend: sqlite
  sqlite_dir: "{info.qilin_data_dir.as_posix()}"

run_events:
  backend: db

skills:
  root: "{info.skill_root.as_posix()}"

sandbox:
  use: qilin.sandbox.local:LocalSandboxProvider
  allow_host_bash: false

memory:
  enabled: false
"""
        info.runtime_config_path.write_text(content, encoding="utf-8")

    def as_dict(self, info: DataSpaceInfo) -> dict[str, object]:
        return {
            "appDataDir": str(info.app_data_dir),
            "activeUserId": info.active_user_id,
            "qilinHome": str(info.qilin_home),
            "qilinDataDir": str(info.qilin_data_dir),
            "runtimeConfigPath": str(info.runtime_config_path),
            "productDbPath": str(info.product_db_path),
            "skillRoot": str(info.skill_root),
            "developmentFallback": info.is_development_fallback,
        }
